apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fkgz9w5rf-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-30b27b5998.i44a.p3.openshiftapps.com/rhtap/rhtap-qe:c84f27235e328295af757c1cc280425d0e7ba439@sha256:aac3d92fc05f9bb4856e7ae07f85ea8ee4b78f59eb650e46a3871dcc1ef833ce
          name: container-image
